export const WORKSPACE_START = "WORKSPACE_START";

export const WORKSPACE_SUCCESS = "WORKSPACE_SUCCESS";

export const WORKSPACE_FAIL = "WORKSPACE_CREATE_FAIL";

export const WORKSPACE_CREATE_START = "WORKSPACE_CREATE_START";

export const WORKSPACE_CREATE_SUCCESS = "WORKSPACE_CREATE_SUCCESS";

export const WORKSPACE_CREATE_FAIL = "WORKSPACE_CREATE_FAIL";
