export const STORES_START = "STORES_START";

export const STORES_SUCCESS = "STORES_SUCCESS";

export const STORES_FAIL = "STORES_LIST_FAIL";

export const STORES_LIST_START = "STORES_LIST_START";

export const STORES_LIST_SUCCESS = "STORES_LIST_SUCCESS";

export const STORES_LIST_FAIL = "STORES_LIST_FAIL";

export const STORES_FIELD_START = "STORES_FIELD_START";

export const STORES_FIELD_SUCCESS = "STORES_FIELD_SUCCESS";

export const STORES_FIELD_FAIL = "STORES_FIELD_LIST_FAIL";