export const STORES_START = "STORES_START";

export const STORES_SUCCESS = "STORES_SUCCESS";

export const STORES_FAIL = "STORES_LIST_FAIL";

export const STORES_LIST_START = "STORES_LIST_START";

export const STORES_LIST_SUCCESS = "STORES_LIST_SUCCESS";

export const STORES_LIST_FAIL = "STORES_LIST_FAIL";

export const STORES_FIELD_START = "STORES_FIELD_START";

export const STORES_FIELD_SUCCESS = "STORES_FIELD_SUCCESS";

export const STORES_FIELD_FAIL = "STORES_FIELD_LIST_FAIL";

export const STORES_DELETE_START = "STORES_DELETE_START";

export const STORES_DELETE_SUCCESS = "STORES_DELETE_SUCCESS";

export const STORES_DELETE_FAIL = "STORES_DELETE_FAIL";

// type get action
export const STORES_GET_ACTION_START = "STORES_GET_ACTION_START";

export const STORES_GET_ACTION_SUCCESS = "STORES_GET_ACTION_SUCCESS";

export const STORES_GET_ACTION_FAIL = "STORES_GET_ACTION_FAIL";

// type create item store
export const STORES_CREATE_ITEM_START = "STORES_CREATE_ITEM_START";

export const STORES_CREATE_ITEM_SUCCESS = "STORES_CREATE_ITEM_SUCCESS";

export const STORES_CREATE_ITEM_FAIL = "STORES_CREATE_ITEM_FAIL";